# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import resources_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(286, 472)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/机器人俯视.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame#frame{\n"
                                 "    background-color: qlineargradient(x0:0, y0:1, x1:1, y1:1,stop:0.4  rgb(107, 128, 210), stop:1 rgb(180, 140, 255));\n"
                                 "border:0px solid red;\n"
                                 "border-radius:30px\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("QFrame{\n"
                                   "    background-color: rgba(255, 255, 255,0);\n"
                                   "border:0px solid red;\n"
                                   "border-radius:30px\n"
                                   "}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("QFrame{\n"
                                   "    background-color: rgb(245, 249, 254);\n"
                                   "border:0px solid red;\n"
                                   "border-radius:30px\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_30.setContentsMargins(10, 10, 10, 8)
        self.verticalLayout_30.setSpacing(4)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_4.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(255, 255, 255, 0);\n"
                                        "image: url(:/buttom/img/更多.png);\n"
                                        "outline: none;\n"
                                        "border:0px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: rgb(220, 220, 220);\n"
                                        "}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_33.addWidget(self.pushButton_4)
        spacerItem = QtWidgets.QSpacerItem(761, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem)
        self.pushButton_1 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_1.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_1.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(255, 255, 255, 0);\n"
                                        "image: url(:/buttom/img/最小化.png);\n"
                                        "outline: none;\n"
                                        "border:0px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: rgb(220, 220, 220);\n"
                                        "}")
        self.pushButton_1.setText("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_33.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(255, 255, 255, 0);\n"
                                        "image: url(:/buttom/img/发送至.png);\n"
                                        "outline: none;\n"
                                        "border:0px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: rgb(220, 220, 220);\n"
                                        "}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_33.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(255, 255, 255, 0);\n"
                                        "image: url(:/buttom/img/关闭.png);\n"
                                        "outline: none;\n"
                                        "border:0px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color:rgb(255, 0, 0);\n"
                                        "}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_33.addWidget(self.pushButton_3)
        self.verticalLayout_30.addWidget(self.frame_9)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setSpacing(12)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setWordWrap(True)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_32.addWidget(self.listWidget)
        self.verticalLayout_30.addLayout(self.horizontalLayout_32)
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        self.frame_12.setStyleSheet("background-color: rgb(229, 229, 229);\n"
                                    "border-radius:15px;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.message = QtWidgets.QLineEdit(self.frame_12)
        self.message.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.message.setFont(font)
        self.message.setStyleSheet("color: rgb(22, 22, 22);\n"
                                   "border:none;")
        self.message.setObjectName("message")
        self.horizontalLayout_36.addWidget(self.message)
        self.widget_29 = QtWidgets.QWidget(self.frame_12)
        self.widget_29.setMinimumSize(QtCore.QSize(32, 32))
        self.widget_29.setMaximumSize(QtCore.QSize(32, 32))
        self.widget_29.setSizeIncrement(QtCore.QSize(0, 2))
        self.widget_29.setStyleSheet("")
        self.widget_29.setObjectName("widget_29")
        self.send = QtWidgets.QPushButton(self.widget_29)
        self.send.setGeometry(QtCore.QRect(0, 0, 32, 32))
        self.send.setStyleSheet("background-color:rgb(137, 217, 97);\n"
                                "image: url(:/buttom/img/发送_send.svg);\n"
                                "outline: none;\n"
                                "border-radius:16px;\n"
                                "padding:8px;")
        self.send.setText("")
        self.send.setObjectName("send")
        self.horizontalLayout_36.addWidget(self.widget_29)
        self.verticalLayout_30.addWidget(self.frame_12)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.message.setPlaceholderText(_translate("MainWindow", "Type Something..."))
